### ISSUE TITLE
[question] Equals of case classes

### ISSUE THREAD

**Issue by james64** [alexarchambault/ammonite-spark#90]
This is not a bug report to almond. But I was hoping to get some insights into why this is happening.
```
org.apache.spark.sql.catalyst.encoders.OuterScopes.addOuterScope(this);
case class X(a: String, b: String)
```
`defined class X`
```
val r = List.range(0,1000).toDS.map(_ => X("a.com", "p")).rdd.distinct.collect
```
`r: Array[X] = Array(X("a.com", "p"), X("a.com", "p"))`
```
r.head.hashCode
r.last.hashCode
```
`res31_0: Int = -1659187031`
`res31_1: Int = -1659187031`
```
r.head.getClass
r.last.getClass
```
`res29_0: Class[T] = class ammonite.$sess.cmd22$Helper$X`
`res29_1: Class[T] = class ammonite.$sess.cmd22$Helper$X`
```
r.head == r.last
```
`res28: Boolean = false`
```
X("a.com", "p") == X("a.com", "p")
```
`res30: Boolean = true`

Equality works as expected if case class is defined in external jar which is brought in as dependency. Which subsystem should I study to understand how this is happening? Thanks

**Comment by alexarchambault** [comment]
It seems adding `final` to `case class X` fixes this.

I'm not super happy with this workaround, all the more that the behavior * without * the `final` is actually correct IMO. There's still a bug without `final`, so that we can't fix that beforehand ourselves. See below for more details.

**Comment by alexarchambault** [comment]
In more detail, Ammonite wraps your code like
```scala
class Wrapper {
  case class X(a: String, b: String)
}
```
and creates a `Wrapper` instance itself. Because it's wrapped in `Wrapper`, `X` actually has a third field, of type `Wrapper`, pointing to the instance created by Ammonite.

Then spark serializes and deserializes `X` instances, along with their `Wrapper` instance. With a `local[*]` master, we typically get one deserialized `Wrapper` instance per executor, hence as many elements as executors in `r` in your example.

Ideally, we could fix that in Ammonite by adding a correct `override def equals(obj: Any): Boolean = …` in `Wrapper`, which would be true for all `Wrapper` instances. But the `equals` methods generated for `X` compares the `Wrapper` instances with `eq`, not with `equals`, which is a first (Scala) bug.

When we add `final`, the (Scala generated) `equals` of `X` doesn't check `Wrapper` at all. That's a bug too (that's https://github.com/scala/bug/issues/4440#issuecomment-365858185), but that fixes things for us by ignoring the different `Wrapper` instances.

**Comment by alexarchambault** [comment]
After some more investigation, it appears this is also an issue with the default spark repl, that's [SPARK-2620](https://issues.apache.org/jira/browse/SPARK-2620).

Don't hesitate to weight on https://github.com/scala/bug/issues/11940, so that we can have a proper fix of this.

**Comment by james64** [comment]
Thanks for explanation and for looking into this so deeply. I see where the problem is now. I have read through issues you linked. It looks like interactive distributed environments will need to live with this for quite a while more...
